all:
  hosts:
    master:
      ansible_host: 192.168.123.141
      ip: 192.168.123.141
      access_ip: 192.168.123.141
    worker:
      ansible_host: 192.168.123.130
      ip: 192.168.123.130
      access_ip: 192.168.123.130
  children:
    kube_control_plane:
      hosts:
        master:
    kube_node:
      hosts:
        worker:
    etcd:
      hosts:
        master:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
