all:
  hosts:
      ansible_host: 192.168.123.199
      ip: 192.168.123.199
      access_ip: 192.168.123.199
    worker1:
      ansible_host: 192.168.123.161
      ip: 192.168.123.161
      access_ip: 192.168.123.161
    worker2:
      ansible_host: 192.168.123.177
      ip: 192.168.123.177
      access_ip: 192.168.123.177
  children:
    kube_control_plane:
      hosts:
        master:
    kube_node:
      hosts:
        worker1:
        worker2:
    etcd:
      hosts:
        master:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}