apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  annotations:
    sidecar.istio.io/inject: "false"
  name: "mobilenet-v2"
spec:
  predictor:
    serviceAccountName: 'sa'
    tensorflow:
      image: "tensorflow/serving:2.5.1"
      storageUri: "s3://kserve-test/mobilenet_v2"